# Generated by Django 3.0.2 on 2020-01-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='cash',
            new_name='cash_assets',
        ),
    ]
