# Generated by Django 3.0.3 on 2020-02-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='date_last_modified',
            new_name='watched_since',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='PortfolioHistory',
        ),
    ]
