# Generated by Django 3.0.3 on 2020-02-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200212_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
