technology = ["MSFT",
              "AAPL",
              "INTC",
              "TSM",
              "CSCO",
              "NVDA",
              "ADBE",
              "ORCL",
              "SAP",
              "CRM",
              "ACN",
              "IBM",
              "ASML",
              "AVGO",
              "TXN",
              "QCOM",
              "FIS",
              "SNE",
              "INTU",
              "UBER",
              "NOW",
              "VMW",
              "AMD",
              "MU",
              "SHOP"]

real_estate = ["AMT",
               "PLD",
               "CCI",
               "SPG",
               "EQIX",
               "PSA",
               "WELL",
               "SBAC",
               "AVB",
               "EQR",
               "DLR",
               "CSPG",
               "O",
               "BXP",
               "WY",
               "VTR",
               "ESS",
               "ARE",
               "CBRE",
               "PEAK",
               "BPY",
               "INVH",
               "MAA",
               "SUI",
               "NLY"]

communication = ["GOOG",
                 "FB",
                 "T",
                 "DIS",
                 "VZ",
                 "CMCSA",
                 "CHL",
                 "NFLX",
                 "CHTR",
                 "TMUS",
                 "AMOV",
                 "VOD",
                 "RELX",
                 "ATVI",
                 "NTES",
                 "BCE",
                 "ORAN",
                 "S",
                 "TEF",
                 "CHA",
                 "SIRI",
                 "EA",
                 "TWTR",
                 "CHT",
                 "SPOT"]

consumer_cyclical = ["AMZN",
                     "BABA",
                     "HD",
                     "TM",
                     "MCD",
                     "NKE",
                     "TSLA",
                     "SBUX",
                     "LOW",
                     "BKNG",
                     "TJX",
                     "JD",
                     "LVS",
                     "GM",
                     "HMC",
                     "MAR",
                     "ROST",
                     "PDD",
                     "MELI",
                     "LULU",
                     "RACE",
                     "VFC",
                     "F",
                     "YUM",
                     "HLT"]

industry_defaults = {"technology" : technology,
                     "real_estate" : real_estate,
                     "communication" : communication,
                     "consumer_cyclical" : consumer_cyclical}